version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes: 
      - ./api:/app
      - ./api/node_modules
  book:
    build: ./book
    ports:
      - "3500:5173"
    # stdin_open: true
    # tty: true
